# Server configurations
server:
  host: "localhost"
  port: 8080

# Credentials
credentials:
  gitlab_token: "glpat-BWcsGBLXz-1yQxzd3BG3"

# RESTful clients
gitlab_client:
  base_url: "https://gitlab.tiendanimal.com:8088/api/v4"
  timeout: 1000
  connection_timeout: 2000