# Server configurations
server:
  host: "localhost"
  port: 8080

# Credentials
gitlab:
  token: "glpat-BWcsGBLXz-1yQxzd3BG3"
  prefix: "ikp_"

database:
  user: root
  password: a300p011
  host: localhost
  port: 3306

# RESTful clients
gitlab_client:
  base_url: "https://gitlab.tiendanimal.com:8088/api/v4"
  timeout: 2000
  connection_timeout: 5000