version: "3.8"

services:
  api:
    container_name: pets-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - app_env=dev
      - SCOPE=docker
    command: ./build/program
    depends_on:
      - db
  db:
    container_name: pets-db
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: 'pets'
      MYSQL_ROOT_PASSWORD: 'a300p011'
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-volume:
    driver: local