version: "3.8"
services:
  api:
    container_name: app
    build: ./
    ports:
      - "8080:8080"
      - "40000:40000"
    environment:
      - app_env=dev
      - SCOPE=docker
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: /dlv --headless --listen=:40000 --api-version=2 exec /app/server
    depends_on:
      - db
  db:
    container_name: model
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: 'pets'
      MYSQL_ROOT_PASSWORD: 'a300p011'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

volumes:
  db-data:
    driver: local