app.env: dev

# mysql
database.user: root
database.password: a300p011
database.host: localhost
database.port: 3306

# rest
gitlab.client.baseurl: https://gitlab.tiendanimal.com:8088/api/v4
gitlab.client.pool.size: 20
gitlab.client.pool.timeout: 20000
gitlab.client.socket.connection-timeout: 50000