app.env: dev
mysql:
  connection-string: root:a300p011@tcp(localhost:3306)/pets?parseTime=True

# rest
gitlab.client.baseurl: https://gitlab.tiendanimal.com:8088/api/v4
gitlab.client.pool.size: 20
gitlab.client.pool.timeout: 20000
gitlab.client.socket.connection-timeout: 50000