app.env: dev

SECRETS_STORE_PROD_CONNECTION_STRING_KEY_NAME: root:a300p011@tcp(localhost:3306)/pets?parseTime=True

# rest-clients
gitlab.client.baseurl: https://gitlab.tiendanimal.com:8088/api/v4
gitlab.client.pool.size: 20
gitlab.client.pool.timeout: 1000
gitlab.client.socket.connection-timeout: 5000