app.env: dev

# gitlab
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 2000
      connection-timeout: 5000
  client:
    gitlab:
      pool: default

# secrets
SECRETS_STORE_PETS-API_PROD_CONNECTION_STRING_KEY_NAME: root:a300p011@tcp(localhost:3306)/pets?parseTime=True
SECRETS_STORE_PETS-API_GITLAB_TOKEN_KEY_NAME: glpat-BWcsGBLXz-1yQxzd3BG3