app.env: dev

# gitlab
rest:
  pool:
    default:
      pool:
        size: 20
        timeout: 2000
        connection-timeout: 5000
  client:
    gitlab:
      pool: default

# secrets
PROD_CONNECTION_STRING: root:a300p011@tcp(localhost:3306)/pets?parseTime=True
GITLAB_TOKEN: glpat-BWcsGBLXz-1yQxzd3BG3