// Code generated by ent, DO NOT EDIT.

package apptype

const (
	// Label holds the string label denoting the apptype type in the database.
	Label = "app_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeApps holds the string denoting the apps edge name in mutations.
	EdgeApps = "apps"
	// Table holds the table name of the apptype in the database.
	Table = "apps_types"
	// AppsTable is the table that holds the apps relation/edge.
	AppsTable = "apps"
	// AppsInverseTable is the table name for the App entity.
	// It exists in this package in order to avoid circular dependency with the "apps" package.
	AppsInverseTable = "apps"
	// AppsColumn is the table column denoting the apps relation/edge.
	AppsColumn = "app_type_id"
)

// Columns holds all SQL columns for apptype fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
