info:
  contact: {}
  description: Create apps, services and infrastructure.
  title: Pets API
  version: "1.0"
paths:
  /ping:
    get:
      description: Health
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Check if the instance is healthy or unhealthy
      tags:
      - Check
swagger: "2.0"
