// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "project_id", Type: field.TypeInt64, Unique: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "app_type_id", Type: field.TypeInt},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "apps_apps_types_apps",
				Columns:    []*schema.Column{AppsColumns[4]},
				RefColumns: []*schema.Column{AppsTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AppsTypesColumns holds the columns for the "apps_types" table.
	AppsTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// AppsTypesTable holds the schema information for the "apps_types" table.
	AppsTypesTable = &schema.Table{
		Name:       "apps_types",
		Columns:    AppsTypesColumns,
		PrimaryKey: []*schema.Column{AppsTypesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		AppsTypesTable,
	}
)

func init() {
	AppsTable.ForeignKeys[0].RefTable = AppsTypesTable
	AppsTypesTable.Annotation = &entsql.Annotation{
		Table: "apps_types",
	}
}
