// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/arielsrv/pets-api/src/main/app/ent/app"
	"github.com/arielsrv/pets-api/src/main/app/ent/apptype"
	"github.com/arielsrv/pets-api/src/main/app/ent/predicate"
)

// AppTypeUpdate is the builder for updating AppType entities.
type AppTypeUpdate struct {
	config
	hooks    []Hook
	mutation *AppTypeMutation
}

// Where appends a list predicates to the AppTypeUpdate builder.
func (atu *AppTypeUpdate) Where(ps ...predicate.AppType) *AppTypeUpdate {
	atu.mutation.Where(ps...)
	return atu
}

// SetName sets the "name" field.
func (atu *AppTypeUpdate) SetName(s string) *AppTypeUpdate {
	atu.mutation.SetName(s)
	return atu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (atu *AppTypeUpdate) SetNillableName(s *string) *AppTypeUpdate {
	if s != nil {
		atu.SetName(*s)
	}
	return atu
}

// AddAppIDs adds the "apps" edge to the App entity by IDs.
func (atu *AppTypeUpdate) AddAppIDs(ids ...int64) *AppTypeUpdate {
	atu.mutation.AddAppIDs(ids...)
	return atu
}

// AddApps adds the "apps" edges to the App entity.
func (atu *AppTypeUpdate) AddApps(a ...*App) *AppTypeUpdate {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return atu.AddAppIDs(ids...)
}

// Mutation returns the AppTypeMutation object of the builder.
func (atu *AppTypeUpdate) Mutation() *AppTypeMutation {
	return atu.mutation
}

// ClearApps clears all "apps" edges to the App entity.
func (atu *AppTypeUpdate) ClearApps() *AppTypeUpdate {
	atu.mutation.ClearApps()
	return atu
}

// RemoveAppIDs removes the "apps" edge to App entities by IDs.
func (atu *AppTypeUpdate) RemoveAppIDs(ids ...int64) *AppTypeUpdate {
	atu.mutation.RemoveAppIDs(ids...)
	return atu
}

// RemoveApps removes "apps" edges to App entities.
func (atu *AppTypeUpdate) RemoveApps(a ...*App) *AppTypeUpdate {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return atu.RemoveAppIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (atu *AppTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, atu.sqlSave, atu.mutation, atu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atu *AppTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := atu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (atu *AppTypeUpdate) Exec(ctx context.Context) error {
	_, err := atu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atu *AppTypeUpdate) ExecX(ctx context.Context) {
	if err := atu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (atu *AppTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apptype.Table, apptype.Columns, sqlgraph.NewFieldSpec(apptype.FieldID, field.TypeInt))
	if ps := atu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atu.mutation.Name(); ok {
		_spec.SetField(apptype.FieldName, field.TypeString, value)
	}
	if atu.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apptype.AppsTable,
			Columns: []string{apptype.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atu.mutation.RemovedAppsIDs(); len(nodes) > 0 && !atu.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apptype.AppsTable,
			Columns: []string{apptype.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atu.mutation.AppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apptype.AppsTable,
			Columns: []string{apptype.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, atu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apptype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	atu.mutation.done = true
	return n, nil
}

// AppTypeUpdateOne is the builder for updating a single AppType entity.
type AppTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppTypeMutation
}

// SetName sets the "name" field.
func (atuo *AppTypeUpdateOne) SetName(s string) *AppTypeUpdateOne {
	atuo.mutation.SetName(s)
	return atuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (atuo *AppTypeUpdateOne) SetNillableName(s *string) *AppTypeUpdateOne {
	if s != nil {
		atuo.SetName(*s)
	}
	return atuo
}

// AddAppIDs adds the "apps" edge to the App entity by IDs.
func (atuo *AppTypeUpdateOne) AddAppIDs(ids ...int64) *AppTypeUpdateOne {
	atuo.mutation.AddAppIDs(ids...)
	return atuo
}

// AddApps adds the "apps" edges to the App entity.
func (atuo *AppTypeUpdateOne) AddApps(a ...*App) *AppTypeUpdateOne {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return atuo.AddAppIDs(ids...)
}

// Mutation returns the AppTypeMutation object of the builder.
func (atuo *AppTypeUpdateOne) Mutation() *AppTypeMutation {
	return atuo.mutation
}

// ClearApps clears all "apps" edges to the App entity.
func (atuo *AppTypeUpdateOne) ClearApps() *AppTypeUpdateOne {
	atuo.mutation.ClearApps()
	return atuo
}

// RemoveAppIDs removes the "apps" edge to App entities by IDs.
func (atuo *AppTypeUpdateOne) RemoveAppIDs(ids ...int64) *AppTypeUpdateOne {
	atuo.mutation.RemoveAppIDs(ids...)
	return atuo
}

// RemoveApps removes "apps" edges to App entities.
func (atuo *AppTypeUpdateOne) RemoveApps(a ...*App) *AppTypeUpdateOne {
	ids := make([]int64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return atuo.RemoveAppIDs(ids...)
}

// Where appends a list predicates to the AppTypeUpdate builder.
func (atuo *AppTypeUpdateOne) Where(ps ...predicate.AppType) *AppTypeUpdateOne {
	atuo.mutation.Where(ps...)
	return atuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (atuo *AppTypeUpdateOne) Select(field string, fields ...string) *AppTypeUpdateOne {
	atuo.fields = append([]string{field}, fields...)
	return atuo
}

// Save executes the query and returns the updated AppType entity.
func (atuo *AppTypeUpdateOne) Save(ctx context.Context) (*AppType, error) {
	return withHooks(ctx, atuo.sqlSave, atuo.mutation, atuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atuo *AppTypeUpdateOne) SaveX(ctx context.Context) *AppType {
	node, err := atuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (atuo *AppTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := atuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atuo *AppTypeUpdateOne) ExecX(ctx context.Context) {
	if err := atuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (atuo *AppTypeUpdateOne) sqlSave(ctx context.Context) (_node *AppType, err error) {
	_spec := sqlgraph.NewUpdateSpec(apptype.Table, apptype.Columns, sqlgraph.NewFieldSpec(apptype.FieldID, field.TypeInt))
	id, ok := atuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := atuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apptype.FieldID)
		for _, f := range fields {
			if !apptype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apptype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := atuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atuo.mutation.Name(); ok {
		_spec.SetField(apptype.FieldName, field.TypeString, value)
	}
	if atuo.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apptype.AppsTable,
			Columns: []string{apptype.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atuo.mutation.RemovedAppsIDs(); len(nodes) > 0 && !atuo.mutation.AppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apptype.AppsTable,
			Columns: []string{apptype.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atuo.mutation.AppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apptype.AppsTable,
			Columns: []string{apptype.AppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AppType{config: atuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, atuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apptype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	atuo.mutation.done = true
	return _node, nil
}
