// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/arielsrv/pets-api/src/main/app/ent/app"
	"github.com/arielsrv/pets-api/src/main/app/ent/schema"
	"github.com/arielsrv/pets-api/src/main/app/ent/secret"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescActive is the schema descriptor for active field.
	appDescActive := appFields[4].Descriptor()
	// app.DefaultActive holds the default value on creation for the active field.
	app.DefaultActive = appDescActive.Default.(bool)
	secretFields := schema.Secret{}.Fields()
	_ = secretFields
	// secretDescActive is the schema descriptor for active field.
	secretDescActive := secretFields[4].Descriptor()
	// secret.DefaultActive holds the default value on creation for the active field.
	secret.DefaultActive = secretDescActive.Default.(bool)
}
