// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ent/app"
	"github.com/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescActive is the schema descriptor for active field.
	appDescActive := appFields[3].Descriptor()
	// app.DefaultActive holds the default value on creation for the active field.
	app.DefaultActive = appDescActive.Default.(bool)
}
