// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// AppType is the predicate function for apptype builders.
type AppType func(*sql.Selector)
